# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 841213e16c6e32b1705b02230a238046fa06cae0e826ef79d84b62d743e934287bbcdb46e94e3774cba8a747e751a4173c077f48e414f50aac4188aa75bca12a

test:
  secret_key_base: cae6d8f9df8e3e6aaf77842cb5a737cb7ed812dda08122aa7214db26c80bafd02b37aec56218d7c0b1401dbce50d3713b6182a0024ee55752d1f59d6f4f47470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
